name: Scrape

on:
  schedule:
    - cron: "15 * * * *"

jobs:
  resources:
    name: Scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Xvfb
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x16 &

      - name: Fetch Resources
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: node ./index.js
