name: Scrape

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  resources:
    name: Scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      

      - name: Fetch Resources
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: node ./index.js
