name: Run Scraper

on:
  schedule:
    - cron: "0 20,23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Setup Xvfb
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x16 &

      - name: Run scraper
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: node index.js
